services:
  - type: web
    name: matrimony-web-application
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn matrimony.wsgi:application"
   
