# Generated by Django 5.2 on 2025-04-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpreference',
            name='max_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='min_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='preferred_location',
            field=models.CharField(choices=[('kerala', 'Kerala'), ('tamilnadu', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='preferred_profession',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('doctor', 'Doctor'), ('teacher', 'Teacher'), ('business', 'Business'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='preferred_religion',
            field=models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('kerala', 'Kerala'), ('tamilnadu', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('doctor', 'Doctor'), ('teacher', 'Teacher'), ('business', 'Business'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('other', 'Other')], max_length=100),
        ),
    ]
