# Generated by Django 4.2.20 on 2025-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_partnerpreference_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
